export const blockTypeNames: Record<number, string> = {
  1: "stone",
  2: "grass block",
  3: "dirt",
  4: "cobblestone",
  5: "wood planks",
  12: "sand",
  17: "wood log",
  280: "stick",
  270: "wooden pickaxe",
  274: "stone pickaxe",
  21: "lapis lazuli ore",
  14: "gold ore",
  15: "iron ore",
  16: "coal ore",
  13: "gravel",
  263: "coal",
  257: "iron pickaxe",
  264: "diamond",
  265: "iron ingot",
  266: "gold ingot",
  278: "diamond pickaxe",
  200: "white wool",
  201: "orange wool",
  202: "magenta wool",
  203: "light blue wool",
  204: "yellow wool",
  205: "lime wool",
  206: "pink wool",
  207: "gray wool",
  208: "light gray wool",
  209: "cyan wool",
  210: "purple wool",
  211: "blue wool",
  212: "brown wool",
  213: "green wool",
  214: "red wool",
  215: "black wool",
  216: "gold block",
  42: "iron block",
  41: "gold block",
  57: "diamond block",
  351: "lapis lazuli",
  22: "lapis lazuli block",
  82: "clay",
  56: "diamond ore",
  24: "sandstone",
}

export const blockImages: Record<string, string> = {
  "grass block": "grassBlock",
  "dirt": "dirt",
  "cobblestone": "cobblestone",
  "wood planks": "woodPlanks",
  "sand": "sand",
  "lapis lazuli ore": "lapisLazuliOre",
  "gold ore": "goldOre",
  "iron ore": "ironOre",
  "coal ore": "coalOre",
  "gravel": "gravel",
  "diamond": "diamond",
  "iron ingot": "iron_ingot",
  "gold ingot": "gold_ingot",
  "lapis lazuli": "lapis_lazuli",
  "sandstone": "sandstone",
  "flower": "flower",
  "white wool": "whiteWool",
  "orange wool": "orangeWool",
  "magenta wool": "magentaWool",
  "light blue wool": "lightBlueWool",
  "yellow wool": "yellowWool",
  "lime wool": "limeWool",
  "pink wool": "pinkWool",
  "gray wool": "grayWool",
  "light gray wool": "lightGrayWool",
  "cyan wool": "cyanWool",
  "purple wool": "purpleWool",
  "blue wool": "blueWool",
  "brown wool": "brownWool",
  "green wool": "greenWool",
  "red wool": "redWool",
  "black wool": "blackWool",
  "gold block": "goldBlock",
  "iron block": "ironBlock",
  "diamond block": "diamondBlock",
  "lapis lazuli block": "lapisLazuliBlock",
  "clay": "clayBlock",
  "diamond ore": "diamondOre",
  "stone": "stone",
  "wood log": "birchWood",
  "stick": "stick",
  "stone pickaxe": "stone_pickaxe",
  "wooden pickaxe": "wooden_pickaxe",
  "iron pickaxe": "iron_pickaxe",
  "gold pickaxe": "golden_pickaxe",
  "diamond pickaxe": "diamond_pickaxe",
  "coal": "coal",
}